feat: Create Pricing Table slice
prismicio/essential-slices pull request #12
Opened 2020-06-04 23:08 UTC by georch

2020-06-04 23:22 UTC, luisduenas commented on src/slices/PricingTable/index.js
> +                sx={{
right now we are using **__css** in theme-ui native components and **sx** for our custom components, let's define which one is the better option

2020-06-04 23:46 UTC, jardix22 requested changes

2020-06-04 23:46 UTC, jardix22 commented on src/slices/PricingTable/meta.json
> +{
Please fix the indentation to use two spaces instead of four. And easy way to do it's running the `yarn format` command.

2020-06-04 23:46 UTC, jardix22 commented on src/slices/PricingTable/mock.json
> +{
The same indentation issue.

2020-06-04 23:46 UTC, jardix22 commented on src/slices/PricingTable/model.json
> +{
The same indentation, too.

2020-06-05 00:07 UTC, jardix22 approved these changes

2020-06-05 00:53 UTC, merged